### ISSUE TITLE
Python Version issue

### ISSUE THREAD

**Issue by bth22** [KirstieJane/NSPN_WhitakerVertes_PNAS2016#11]
Hi, do you know which version of Python you used?  I'm using 2.7.13 and getting the following error.

```
COHORT: DISCOVERY
--------------------------------------------------
Making or loading correlation matrices
    CT_ALL_COVARS_ONES
    CT_ADULT_COVARS_ONES
--------------------------------------------------
Filling measure dict with regional values and correlations with age
Traceback (most recent call last):
  File "NSPN_CorticalMyelination_AnalysisWrapper.py", line 217, in <module>
    n_perm=1000)
  File "/Users/taylorhilton/Downloads/NSPN_WhitakerVertes_PNAS2016-master/SCRIPTS/fill_measure_dict.py", line 49, in fill_measure_dict_part1
    fsaverage_dict['centroids'])
  File "/Users/taylorhilton/Downloads/NSPN_WhitakerVertes_PNAS2016-master/SCRIPTS/fill_measure_dict.py", line 264, in save_name_lists
    list_34 += [ measure_dict['308'][measure][i[0]] ]
TypeError: only integer scalar arrays can be converted to a scalar index
```

**Comment by bth22** [comment]
To clarify this is for NSPN_CorticalMyelination_AnalysisWrapper.py.

**Comment by KirstieJane** [comment]
Aaaah! That's so sad @bth22 😢 

I was using 2.7.x but I didn't write down the exact version. Bad Kirstie. 🙍 

I'll try to have a play next week and see if I can replicate the error. Fingers crossed its an easy fix. Thank you for letting me know :)

**Comment by bth22** [comment]
Did you have a chance to look at it?  I appreciate the help.  :)

**Comment by jlhanson5** [comment]
bth22 (Taylor) was in my research group and we were interested in trying this (or similar) code out. Is it better to try this code... or the WhitakerLab/BrainNetworksInPython github? Thanks much in advance!
